"""added columns

Revision ID: 4c4b0b2ed302
Revises: d1794e7f5b4e
Create Date: 2024-07-31 21:00:31.692904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c4b0b2ed302'
down_revision = 'd1794e7f5b4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_service',
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_appointment_service_appointment_id_appointments')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_appointment_service_service_id_services')),
    sa.PrimaryKeyConstraint('appointment_id', 'service_id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('stylist_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_appointments_stylist_id_stylists'), 'stylists', ['stylist_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_appointments_client_id_clients'), 'clients', ['client_id'], ['id'])

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('stylist_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_clients_stylist_id_stylists'), 'stylists', ['stylist_id'], ['id'])

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))

    with op.batch_alter_table('stylists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stylists', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('price')
        batch_op.drop_column('type')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_clients_stylist_id_stylists'), type_='foreignkey')
        batch_op.drop_column('stylist_id')
        batch_op.drop_column('email')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_appointments_client_id_clients'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_appointments_stylist_id_stylists'), type_='foreignkey')
        batch_op.drop_column('client_id')
        batch_op.drop_column('stylist_id')
        batch_op.drop_column('time')
        batch_op.drop_column('date')

    op.drop_table('appointment_service')
    # ### end Alembic commands ###
