"""updated models

Revision ID: 51cac882de8d
Revises: 585a1d40a001
Create Date: 2024-08-01 20:01:07.102929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51cac882de8d'
down_revision = '585a1d40a001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment_service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment_service', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
