"""empty message

Revision ID: 708f1e08b7cf
Revises: fa0bb3d3d7e8
Create Date: 2024-08-13 19:51:46.860462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '708f1e08b7cf'
down_revision = 'fa0bb3d3d7e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
