"""removeved excess relationships

Revision ID: 7dc1606703f8
Revises: 51cac882de8d
Create Date: 2024-08-06 20:51:09.301583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dc1606703f8'
down_revision = '51cac882de8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment_service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(), nullable=True))
        batch_op.drop_column('quantity')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint('fk_clients_stylist_id_stylists', type_='foreignkey')
        batch_op.drop_column('stylist_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stylist_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_clients_stylist_id_stylists', 'stylists', ['stylist_id'], ['id'])

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('appointment_service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), nullable=False))
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
